apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
  namespace: spire
data:
  k8s-workload-registrar.conf: |
    trust_domain = "example.org"
    server_socket_path = "/tmp/spire-server/private/api.sock"
    cluster = "example-cluster"
    mode = "crd"
    pod_annotation = "spiffe.io/spiffe-id"


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: k8s-workload-registrar
#   namespace: spire
# data:
#   k8s-workload-registrar.conf: |
#     trust_domain = "example.org"
#     server_socket_path = "/tmp/spire-server/private/api.sock"
#     cluster = "k8stest"
#     mode = "reconcile"
#     pod_label = "spire-workload"
#     metrics_addr = "0"
