apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-workload
  namespace: spire
  labels:
    app: example-workload
spec:
  selector:
    matchLabels:
      app: example-workload
  template:
    metadata:
      namespace: spire
      labels:
        app: example-workload
      annotations:
        spiffe.io/spiffe-id: "testing/example-workload"
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: example-workload
          image: gcr.io/spiffe-io/spire-agent:0.12.0
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/dumb-init", "/opt/spire/bin/spire-agent", "api", "watch"]
          args: ["-socketPath", "/tmp/spire-agent/public/api.sock"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /tmp/spire-agent/public
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory
