version: '3'
services:
  graphite-statsd:
    image: graphiteapp/graphite-statsd:1.1.7-6
    container_name: graphite
    hostname: graphite-statsd
    restart: always
    ports:
        - "80:80"
        - "8125:8125/udp"
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
  spire-server:
    image: gcr.io/spiffe-io/spire-server:0.11.0
    hostname: spire-server
    volumes:
        - ./spire/server:/opt/spire/conf/server
    command: ["-config", "/opt/spire/conf/server/server.conf"]
  spire-agent:
    image: gcr.io/spiffe-io/spire-agent:0.11.0
    depends_on: ["spire-server"]
    hostname: spire-agent
    volumes:
        - ./spire/agent:/opt/spire/conf/agent
        - /var/run/:/var/run/
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
